routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

//Staff Form
Route::namespace('Staff')->group(function (){
    Route::get('/staff','StaffController@get')->name('staff.index');
    Route::post('/staff/add','StaffController@store');
    Route::get('/staff/delete','StaffController@destroy');
    Route::get('/staff/find','StaffController@find');
    Route::get('/staff/{name}','StaffController@detail')->name('staff.detail');
});
//Position Form
Route::namespace('Position')->group(function (){
    Route::get('/position','PositionController@index')->name('position.index');
    Route::post('/position/add','PositionController@store');
    Route::get('/position/delete','PositionController@destroy');
    Route::get('/position/find','PositionController@find');
    Route::get('/position/{name}','PositionController@detail')->name('position.detail');
});
//Warehousebook Form
Route::namespace('WareHouse')->group(function () {
    Route::get('/warehouse-book', 'WarehouseController@index')->name('warehouse-book.index');
    Route::get('/warehouse-book/pdf', 'WarehouseController@createPDF')->name('warehouse.pdf');
    Route::get('/warehouse-book/delete','WarehouseController@destroy')->name('warehouse.del');
    Route::get('/warehouse-book/trash','WarehouseController@trash')->name('product_trash');
    Route::get('/product-trash/{id}','WarehouseController@ultras')->name('product_ultras');
    Route::get('/product-trash/force','WarehouseController@force')->name('product_force');
});
//Book Form
Route::namespace('Book')->group(function (){
    Route::get('/book','BookController@index')->name('book.index');
    Route::post('book/add','BookController@store');
    Route::get('/book/delete','BookController@destroy');
    Route::get('/warehouse_book','BookController@warehouse');
    Route::get('/book/find','BookController@find');
    Route::get('/book/{name}','BookController@detail')->name('book.detail');
    Route::post('book/send','BookController@send')->name('book.send');

});
//Customer Form
Route::namespace('Customer')->group(function (){
    Route::get('/customer-book','CustomerController@sell')->name('customer-book.index');
    Route::post('sell/add','CustomerController@store')->name('sell.activate');
    Route::get('/register-book','CustomerController@register')->name('register-book.index');
    Route::get('/price','InternShipController@price')->name('internship.price');


});

//Chart Form
Route::namespace('Chart')->group(function () {
    Route::get('/chart', 'ChartController@index')->name('chart.index');
});


//Teacherbook Form
Route::namespace('TeacherBook')->group(function (){
    Route::get('/teacher-book','TeacherBookController@index')->name('teacher-book.index');
});

//Topic Form
Route::namespace('Topic')->group(function (){
    Route::get('/topic','TopicController@index')->name('topic.index');
    Route::post('/topic/add','TopicController@store')->name('topic.add');
    Route::get('/topic/delete','TopicController@destroy')->name('topic.delete');
    Route::get('/topic/find','TopicController@find')->name('topic.find');
    Route::get('/topic/{name}','TopicController@detail')->name('topic.detail');
});




//Internship and Register Internship Form
Route::namespace('Internship')->group(function (){
    Route::get('/internship','InternShipController@index')->name('internship.index');
    Route::post('/internship/add','InternShipController@store')->name('internship.add');
    Route::get('/intern/delete','InternShipController@destroy')->name('internship.delete');
    Route::get('/internship/complete','InternShipController@trash')->name('internship.complete');
    Route::get('/complete/{id}','InternShipController@unfinished')->name('internship.unfinished');
    Route::get('/intern','InternShipController@show')->name('intern.index');
    Route::get('/ajax','InternShipController@ajax')->name('internship.ajax');
    Route::get('/filter1','InternShipController@filter1')->name('filter1.index');
    Route::get('/filter2','InternShipController@filter2')->name('filter2.index');
    Route::get('/filter3','InternShipController@filter3')->name('filter3.index');
    Route::get('/filter4','InternShipController@filter4')->name('filter4.index');
    Route::get('/filter4','InternShipController@filter4')->name('filter4.index');

});


//Course form
Route::resource('/course', 'CourseController', ['only' => ['index', 'store', 'destroy']]);
Route::get('/course/find', 'CourseController@find');
Route::get('/course/{id}', 'CourseController@detail')->name('course.detail');
Route::get('/course/student-list/{id}', 'CourseController@studentList')->name('course.student-list');
Route::post('/course/student-list/confirm/action', 'CourseController@confirm')->name('course.confirm');

//Certification
Route::resource('/certification', 'CertificationController', ['only' => ['index', 'store', 'destroy', 'show', 'edit']]);
Route::get('/certification/export/{id}', 'CertificationController@export')->name('certification.export');
Route::get('/certification/find/{value}', 'CertificationController@find');
Route::get('/certification/detail/{id}', 'CertificationController@detail')->name('certification.detail');

//Student form
Route::resource('/student', 'StudentController', ['only' => ['index', 'store', 'destroy']]);
Route::get('/student/find', 'StudentController@find');
Route::get('/student/{id}', 'StudentController@detail')->name('student.detail');
//Register course
Route::get('/student/register-course/index', 'StudentController@register')->name('student.register-index');
Route::get('/student/register-course/{id}', 'StudentController@registerCourse')->name('student.register-course');
Route::get('/student/register-course/info/{id}', 'StudentController@info')->name('student.info');
Route::get('/student/register-course/add-cart/{id}', 'StudentController@addCart')->name('student.add-cart');
Route::get('/student/register-course/delete-cart/{id}', 'StudentController@deleteCart');

//Receipt
Route::resource('/receipt', 'ReceiptController', ['only' => ['index', 'destroy']]);
Route::get('/receipt/review/{id}', 'ReceiptController@reviewReceipt')->name('receipt.review');
Route::get('/receipt/find', 'ReceiptController@find');
Route::get('/receipt/{id}', 'ReceiptController@detail')->name('receipt.detail');

//Receipt different form
Route::resource('/receipt-different', 'ReceiptDifferentController', ['only' => ['index', 'store', 'destroy']]);
Route::get('/receipt-different/review/{id}', 'ReceiptDifferentController@reviewReceipt')->name('receipt-different.review');
Route::get('/receipt-different/find', 'ReceiptDifferentController@find');
Route::get('/receipt-different/{id}', 'ReceiptDifferentController@detail')->name('receipt-different.detail');

//Cash book
Route::resource('/cash-book', 'CashBookController', ['only' => ['index', 'destroy']]);
Route::get('/cash-book/statistic', 'CashBookController@statistic')->name('cash-book.statistic');

//Class form
Route::resource('/class', 'ClassController', ['only' => ['index', 'store', 'destroy']]);
Route::get('/class/find', 'ClassController@find');
Route::get('/class/{name}', 'ClassController@detail')->name('class.detail');

//Campus form
Route::resource('/campus', 'CampusController', ['only' => ['index', 'store', 'destroy']]);
Route::get('/campus/find', 'CampusController@find');
Route::get('/campus/{name}', 'CampusController@detail')->name('campus.detail');
Route::get('/campus/class-list/{code}', 'CampusController@classList')->name('campus.class-list');

//Check unique
Route::get('/unique-std', 'UniqueController@uniqueStd');
Route::get('/unique-camp', 'UniqueController@uniqueCamp');
Route::get('/unique-period', 'UniqueController@uniquePeriod');
Route::get('/unique-course', 'UniqueController@uniqueCourse');
Route::get('/unique-staff', 'UniqueController@uniqueStaff');
Route::get('/unique-book', 'UniqueController@uniqueBook');
Route::get('/unique-position', 'UniqueController@uniquePosition');
Route::get('/unique-register', 'UniqueController@uniqueRegister');

//Period form
Route::resource('/period', 'PeriodController', ['only' => ['index', 'store', 'destroy']]);
Route::get('/period/find', 'PeriodController@find');
Route::get('/period/{name}', 'PeriodController@detail')->name('period.detail');

//Schedule form
Route::resource('/schedule', 'ScheduleController', ['only' => ['index', 'store', 'destroy', 'show']]);
Route::get('/schedule/find/{value}', 'ScheduleController@find');
Route::get('/schedule/detail/{id}', 'ScheduleController@detail')->name('schedule.detail');
Route::get('/schedule/general/index', 'ScheduleController@general')->name('schedule.general');
Route::get('/schedule/general/class/{id}', 'ScheduleController@generalClass')->name('schedule.class');
Route::get('/schedule/general/teacher/{id}', 'ScheduleController@generalTeacher')->name('schedule.teacher');

Auth::routes();

//Role
Route::resource('/role', 'RoleController', ['only' => ['index', 'store', 'destroy']]);

//User
Route::resource('/user', 'UserController', ['only' => ['index', 'store', 'destroy']]);

app/Models/Receipt.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Receipt extends Model
{
    protected $table = 'receipts';

    protected $fillable = [
        'code', 'student_id', 'schedule_id', 'register_time', 'reason',
        'advance_money', 'total_money', 'remain_money', 'money_text'
    ];

    public function createCode() {
        //Get date now
        $now = Carbon::now();
        $year = $now->year;
        $receipt = Receipt::get()->last();
        $code = "PT-TQ/".$year.'/0001';
        if ($receipt != null) {
            $string = explode('/', $receipt->code);
            $previousCode = (integer)$string[2]; //9
            if ($previousCode > 8) {
                $code = "PT-TQ/".$year.'/00'.($previousCode + 1);
            }
            elseif ($previousCode > 98) {
                $code = "PT-TQ/".$year.'/0'.($previousCode + 1);
            }
            elseif ($previousCode > 998) {
                $code = "PT-TQ/".$year.'/'.($previousCode + 1);
            }
            else {
                $code = "PT-TQ/".$year.'/000'.($previousCode + 1);
            }
        }
        return $code;
    }

    public function resetMembershipInClass($id, $require) {
        $receipt = DB::table('receipts')
            ->join('students', 'students.id','=', 'receipts.student_id')
            ->where('receipts.id', '=', $id)->first();
        //Check total schedule in receipts table
        $allReceipt = Receipt::get();
        $allSchedule = new Collection();
        foreach ($allReceipt as $item) {
            $schedule = explode(' ', $item->schedule_id);
            foreach ($schedule as $item2) {
                if ($item2 !== '')  {
                    $allSchedule->push($item2);
                }
            }
        }
        //Current schedule
        $currentSchedule = new Collection();
        $string = explode(' ', $receipt->schedule_id);
        foreach ($string as $item) {
            if ($item !== '')  {
                //Get membership of current schedules
                $count = 0;
                foreach ($allSchedule as $item2) {
                    if ($item2 === $item) {
                        $count++;
                    }
                }
                $currentSchedule->put($item, $count);
            }
        }
        //Update membership in class (current schedule)
        foreach ($string as $item) {
            if ($item !== '')  {
                $query = DB::table('schedules')
                    ->join('classes', 'classes.id', '=', 'schedules.class_id')
                    ->where('schedules.id', '=', $item)
                    ->select('schedules.*', 'classes.membership as class_membership')
                    ->first();
                if ($require == 'minus') {
                    $newMembership = $query->class_membership - $currentSchedule->get($item);
                    //Save new membership
                    $schedule = Schedule::find($item);
                    $schedule->membership = $newMembership;
                    $schedule->save();
                }
                else {
                    //Save new membership
                    $schedule = Schedule::find($item);
                    $schedule->membership += 1;
                    $schedule->save();
                }
            }
        }
    }

    public function read($code) {
        $receipt = DB::table('receipts')
            ->join('students', 'students.id', '=', 'receipts.student_id')
            ->select('receipts.*', 'students.id as student_id','students.name as name', 'students.phone_number as phone_number', 'students.email as email')
            ->where('receipts.code', '=', $code)
            ->first();
        if ($receipt != null) {
            //Get id, name of courses
            $course_name = '';
            $course_id = '';
            $scheduleText = explode(' ', $receipt->schedule_id);
            for ($i = 0; $i < sizeof($scheduleText); $i++) {
                if ($scheduleText[$i] !== '') {
                    $query = DB::table('schedules')
                        ->join('courses', 'courses.id', '=', 'schedules.course_id')
                        ->where('schedules.id', '=', $scheduleText[$i])
                        ->select('courses.name as course_name', 'courses.id as course_id')
                        ->first();
                    $course_id .= $query->course_id;
                    $course_name .= $query->course_name;
                    if ($i < (sizeof($scheduleText) - 2)) {
                        $course_id .= ', ';
                        $course_name .= ', ';
                    }
                }
            }
            $receipt->course_id = $course_id;
            $receipt->course_name = $course_name;

            return $receipt;
        }
    }

}

resources/views/receipt/cash_different_pdf.blade.php
<style>
    p {
        margin-top: 1px;
        margin-bottom: 1px;
    }
    br {
        margin-top: 1px;
        margin-bottom: 1px;
        margin-left: 0;
        margin-right: 0;
    }
    .col-left {
        width: 30%;
    }
    .col-right {
        width: 70%;
    }
    .border-dotter {
        border-bottom: 1px dotted;
    }
</style>

<div style="font-family: DejaVu Sans, sans-serif; border: ridge; margin: 0 10% 0 10%; font-size: 16px">
    <div style="margin: 10px 10px 20% 10px">
        <div class="clearfix">
            <p><b>Đơn vị:</b> Trung tâm Tin Học và Ngoại ngữ Thiên Quân</p>
            <p style="float: right">Mã phiếu: {{ $receipt->code }}</p>
            <p><b>Địa chỉ:</b> 1234, AAA</p>
        </div>
        <p style="text-align: center; font-size: 30px; margin-bottom: 0px"><b>Phiếu Thu</b></p>
        @php /** @var TYPE_NAME $receipt */
            $now = \Carbon\Carbon::parse(date($receipt->register_time)) @endphp
        <p style="text-align: center">Ngày {{ $now->day }} tháng {{ $now->month }} năm {{ $now->year }}</p>
        <div class="clearfix">
            <table class="table table-borderless table-sm" width="100%" style="font-size: 16px; margin: 0 auto">
                <tr class="table-light">
                    <td class="col-left">Họ tên người nộp tiền:</td>
                    <td class="col-right">
                        <p class="border-dotter">{{ $receipt->name }}</p>
                    </td>
                </tr>
                <tr>
                    <td class="col-left">Địa chỉ:</td>
                    <td class="col-right">
                        <p class="border-dotter">{{ $receipt->address }}</p>
                    </td>
                </tr>
                <tr class="table-light">
                    <td class="col-left">Lý do nộp:</td>
                    <td class="col-right">
                        <p class="border-dotter">{{ $receipt->reason }}</p>
                    </td>
                </tr>
                <tr>
                    <td class="col-left">Tổng số tiền:</td>
                    <td class="col-right">
                        <p class="border-dotter">{{ number_format($receipt->total_money,0,',','.') }} VND</p>
                    </td>
                </tr>
                <tr class="table-light">
                    <td class="col-left">(Viết bằng chữ):</td>
                    <td class="col-right">
                        <p class="border-dotter">{{ $receipt->money_text }}</p>
                    </td>
                </tr>
            </table>
        </div>
        <p style="text-align: right">Ngày {{ $now->day }} tháng {{ $now->month }} năm {{ $now->year }}</p>
        <div class="clearfix">
            <p style="float: right; padding-right: 20px"><b>Người lập phiếu</b></p>
            <p style="float: left; padding-left: 20px"><b>Người nộp tiền</b></p>
        </div>
    </div>
</div>

resources/views/receipt/receipt.blade.php
@extends('layout.master')
@section('css')
    <link rel="stylesheet" href="{{ asset('css/course.css') }}">
@endsection
@section('javascript')
    <script>
        $(".chosen-select").chosen({ width: "100%" });
    </script>
@endsection
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">{{ __('student.register_course') }}</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('home') }}">{{ __('action.home') }}</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

            <div class="clearfix header-course">
                @can('superAdmin')
                    <a class="btn btn-primary" href="{{ route('student.register-index') }}" role="button">{{ __('action.register_course') }}</a>
                @elsecan('create')
                    <a class="btn btn-primary" href="{{ route('student.register-index') }}" role="button">{{ __('action.register_course') }}</a>
                @endcan
                @if(session('success'))
                    <div class="alert alert-success abc" role="alert">
                        {{ session('success') }}
                    </div>
                @endif
                @if(session('fail'))
                    <div class="alert alert-danger abc" role="alert">
                        {{ session('fail') }}
                    </div>
                @endif
            </div>

            <div class="panel panel-default">
                <div class="panel-heading"></div>

                <div class="panel-body table-responsive">
                    <div>
                        <table class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th style="text-align: center"><input type="checkbox" id="check-all"></th>
                                <th style="text-align: center" scope="col">{{__('action.id')}}</th>
                                <th scope="col">{{__('receipt.code')}}</th>
                                <th scope="col">{{__('student.student')}}</th>
                                <th scope="col">{{__('course.course')}}</th>
                                <th></th>
                            </tr>
                            </thead>

                            <tbody>
                            @foreach ($receipt as $item => $data)
                                <tr>
                                    <td class="align-middle" style="text-align: center"><input type="checkbox" class="btn-check"></td>
                                    <th class="align-middle" style="text-align: center" scope="row">{{ $receipt->firstItem() + $item }}</th>
                                    <td class="align-middle">{{ $data->code }}</td>
                                    <td class="align-middle" id="index">
                                        <p>{{ $data->name }}</p>
                                        <p style="color: grey; font-size: 13px">{{ $data->phone_number.' - '.$data->email }}</p>
                                    </td>
                                    <td class="align-middle">{{ $data->course_name }}</td>
                                    <td class="align-middle">
                                        <button type="button" class="receipt btn btn-xs btn-info" data-toggle="modal" data-target="#exampleModal{{ $data->id }}" data-id="{{ $data->id }}">
                                            {{ __('action.review_receipt') }}
                                        </button>

                                        <div class="modal fade" id="exampleModal{{ $data->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog modal-lg" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">{{ __('student.info_receipt') }}</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body"></div>
                                                    <div class="modal-footer" style="width: 100%; margin-right: 10%; margin-bottom: 20px">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('action.close') }}</button>
                                                        @can('create')
                                                            <a style="margin-right: 10%" class="btn btn-primary" href="{{ route('receipt.review', $data->id).'?export=true' }}" role="button">{{ __('student.export_save') }}</a>
                                                        @elsecan('superAdmin')
                                                            <a style="margin-right: 10%" class="btn btn-primary" href="{{ route('receipt.review', $data->id).'?export=true' }}" role="button">{{ __('student.export_save') }}</a>
                                                        @elsecan('update', \App\Models\Student::find($data->student_id))
                                                            <a style="margin-right: 10%" class="btn btn-primary" href="{{ route('receipt.review', $data->id).'?export=true' }}" role="button">{{ __('student.export_save') }}</a>
                                                        @endcan
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        @can('update')
                                            <a class="btn btn-xs btn-success" href="{{ route('student.register-index').'?courses='.$data->course_id.'&student_id='.$data->student_id.'&receipt_id='.$data->id }}" role="button">{{ __('action.update') }}</a>
                                        @elsecan('superAdmin')
                                            <a class="btn btn-xs btn-success" href="{{ route('student.register-index').'?courses='.$data->course_id.'&student_id='.$data->student_id.'&receipt_id='.$data->id }}" role="button">{{ __('action.update') }}</a>
                                        @endcan

                                        @can('delete')
                                            <button type="button" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#exampleModalDelete{{ $data->id }}">
                                                {{__('action.delete')}}
                                            </button>
                                        @elsecan('superAdmin')
                                            <button type="button" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#exampleModalDelete{{ $data->id }}">
                                                {{__('action.delete')}}
                                            </button>
                                        @endcan

                                        <form class="form-container" action="{{ route('receipt.destroy', $data->id) }}" method="POST">
                                            <input name="_method" type="hidden" value="DELETE">
                                            <div class="modal fade" id="exampleModalDelete{{ $data->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="exampleModalLabel">{{__('student.info_regis')}}</h5>
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            @csrf
                                                            <div class="form-group">
                                                                <input style="display: none" type="text" name="id" class="form-control" id="exampleInputStt" value="{{ $data->id }}">
                                                            </div>
                                                            <p>{{__('action.confirm_delete')}}</p>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">{{__('action.close')}}</button>
                                                            <button type="submit" class="btn btn-primary">{{__('action.delete')}}</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>

                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="clearfix">
                        <div style="float: right">
                            {!! $receipt->links() !!}
                        </div>
                    </div>
                </div>
            </div>

        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <script type="text/javascript">
        $(document).ready(function() {

            //Check all checkbox
            $("#check-all").click(function () {
                $('input:checkbox').not(this).prop('checked', this.checked);
            });

            //Review receipt
            $(".receipt").each(function () {
                $(this).on('click', function () {
                    var receipt_id = $(this).data('id');
                    console.log(receipt_id);
                    var url = '{{ route("receipt.review", ":input") }}';
                    url = url.replace(':input', receipt_id);
                    var id = $(this).data('target');
                    $.ajax({
                        url: url,
                        type: "GET",
                    }).done(function (response) {
                        $(id).find(".modal-body").first().empty();
                        $(id).find(".modal-body").first().html(response);
                    });
                })
            });

            var engine1 = new Bloodhound({
                remote: {
                    url: '/receipt/find?value=%QUERY%',
                    wildcard: '%QUERY%'
                },
                datumTokenizer: Bloodhound.tokenizers.whitespace('value'),
                queryTokenizer: Bloodhound.tokenizers.whitespace
            });

            $(".search-input").typeahead({
                hint: true,
                highlight: true,
                minLength: 1
            }, [
                {
                    source: engine1.ttAdapter(),
                    name: 'receipt-code',
                    limit: 20,
                    display: function(data) {
                        return data.code;
                    },
                    templates: {
                        empty: [
                            '<div class="list-group search-results-dropdown"><div class="list-group-item">{{ __('receipt.empty') }}</div></div>'
                        ],
                        header: [
                        ],
                        suggestion: function (data) {
                            var url = '{!! route("receipt.detail", ":input") !!}';
                            url = url.replace(':input', data.id);
                            return '<a style="width: 200%" href="' + url + '" class="list-group-item">' + data.name + ' (' + data.phone_number + ')' + ' - ' + data.code + '</a>';
                        }
                    }
                },
            ]);

        });
    </script>
@stop