routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

//Staff Form
Route::namespace('Staff')->group(function (){
    Route::get('/staff','StaffController@get')->name('staff.index');
    Route::post('/staff/add','StaffController@store');
    Route::get('/staff/delete','StaffController@destroy');
    Route::get('/staff/find','StaffController@find');
    Route::get('/staff/{name}','StaffController@detail')->name('staff.detail');
});
//Position Form
Route::namespace('Position')->group(function (){
    Route::get('/position','PositionController@index')->name('position.index');
    Route::post('/position/add','PositionController@store');
    Route::get('/position/delete','PositionController@destroy');
    Route::get('/position/find','PositionController@find');
    Route::get('/position/{name}','PositionController@detail')->name('position.detail');
});
//Warehousebook Form
Route::namespace('WareHouse')->group(function () {
    Route::get('/warehouse-book', 'WarehouseController@index')->name('warehouse-book.index');
    Route::get('/warehouse-book/pdf', 'WarehouseController@createPDF')->name('warehouse.pdf');
    Route::get('/warehouse-book/delete','WarehouseController@destroy')->name('warehouse.del');
    Route::get('/warehouse-book/trash','WarehouseController@trash')->name('product_trash');
    Route::get('/product-trash/{id}','WarehouseController@ultras')->name('product_ultras');
    Route::get('/product-trash/force','WarehouseController@force')->name('product_force');
});
//Book Form
Route::namespace('Book')->group(function (){
    Route::get('/book','BookController@index')->name('book.index');
    Route::post('book/add','BookController@store');
    Route::get('/book/delete','BookController@destroy');
    Route::get('/warehouse_book','BookController@warehouse');
    Route::get('/book/find','BookController@find');
    Route::get('/book/{name}','BookController@detail')->name('book.detail');
    Route::post('book/send','BookController@send')->name('book.send');

});
//Customer Form
Route::namespace('Customer')->group(function (){
    Route::get('/customer-book','CustomerController@sell')->name('customer-book.index');
    Route::post('sell/add','CustomerController@store')->name('sell.activate');
    Route::get('/register-book','CustomerController@register')->name('register-book.index');
    Route::get('/price','InternShipController@price')->name('internship.price');


});

//Chart Form
Route::namespace('Chart')->group(function () {
    Route::get('/chart', 'ChartController@index')->name('chart.index');
});


//Teacherbook Form
Route::namespace('TeacherBook')->group(function (){
    Route::get('/teacher-book','TeacherBookController@index')->name('teacher-book.index');
});

//Topic Form
Route::namespace('Topic')->group(function (){
    Route::get('/topic','TopicController@index')->name('topic.index');
    Route::post('/topic/add','TopicController@store')->name('topic.add');
    Route::get('/topic/delete','TopicController@destroy')->name('topic.delete');
    Route::get('/topic/find','TopicController@find')->name('topic.find');
    Route::get('/topic/{name}','TopicController@detail')->name('topic.detail');
});




//Internship and Register Internship Form
Route::namespace('Internship')->group(function (){
    Route::get('/internship','InternShipController@index')->name('internship.index');
    Route::post('/internship/add','InternShipController@store')->name('internship.add');
    Route::get('/intern/delete','InternShipController@destroy')->name('internship.delete');
    Route::get('/internship/complete','InternShipController@trash')->name('internship.complete');
    Route::get('/complete/{id}','InternShipController@unfinished')->name('internship.unfinished');
    Route::get('/intern','InternShipController@show')->name('intern.index');
    Route::get('/ajax','InternShipController@ajax')->name('internship.ajax');
    Route::get('/filter1','InternShipController@filter1')->name('filter1.index');
    Route::get('/filter2','InternShipController@filter2')->name('filter2.index');
    Route::get('/filter3','InternShipController@filter3')->name('filter3.index');
    Route::get('/filter4','InternShipController@filter4')->name('filter4.index');
    Route::get('/filter4','InternShipController@filter4')->name('filter4.index');

});


//Course form
Route::resource('/course', 'CourseController', ['only' => ['index', 'store', 'destroy']]);
Route::get('/course/find', 'CourseController@find');
Route::get('/course/{id}', 'CourseController@detail')->name('course.detail');
Route::get('/course/student-list/{id}', 'CourseController@studentList')->name('course.student-list');
Route::post('/course/student-list/confirm/action', 'CourseController@confirm')->name('course.confirm');

//Certification
Route::resource('/certification', 'CertificationController', ['only' => ['index', 'store', 'destroy', 'show', 'edit']]);
Route::get('/certification/export/{id}', 'CertificationController@export')->name('certification.export');
Route::get('/certification/find/{value}', 'CertificationController@find');
Route::get('/certification/detail/{id}', 'CertificationController@detail')->name('certification.detail');

//Student form
Route::resource('/student', 'StudentController', ['only' => ['index', 'store', 'destroy']]);
Route::get('/student/find', 'StudentController@find');
Route::get('/student/{id}', 'StudentController@detail')->name('student.detail');
//Register course
Route::get('/student/register-course/index', 'StudentController@register')->name('student.register-index');
Route::get('/student/register-course/{id}', 'StudentController@registerCourse')->name('student.register-course');
Route::get('/student/register-course/info/{id}', 'StudentController@info')->name('student.info');
Route::get('/student/register-course/add-cart/{id}', 'StudentController@addCart')->name('student.add-cart');
Route::get('/student/register-course/delete-cart/{id}', 'StudentController@deleteCart');

//Receipt
Route::resource('/receipt', 'ReceiptController', ['only' => ['index', 'destroy']]);
Route::get('/receipt/review/{id}', 'ReceiptController@reviewReceipt')->name('receipt.review');
Route::get('/receipt/find', 'ReceiptController@find');
Route::get('/receipt/{id}', 'ReceiptController@detail')->name('receipt.detail');

//Receipt different form
Route::resource('/receipt-different', 'ReceiptDifferentController', ['only' => ['index', 'store', 'destroy']]);
Route::get('/receipt-different/review/{id}', 'ReceiptDifferentController@reviewReceipt')->name('receipt-different.review');
Route::get('/receipt-different/find', 'ReceiptDifferentController@find');
Route::get('/receipt-different/{id}', 'ReceiptDifferentController@detail')->name('receipt-different.detail');

//Cash book
Route::resource('/cash-book', 'CashBookController', ['only' => ['index', 'destroy']]);
Route::get('/cash-book/statistic', 'CashBookController@statistic')->name('cash-book.statistic');

//Class form
Route::resource('/class', 'ClassController', ['only' => ['index', 'store', 'destroy']]);
Route::get('/class/find', 'ClassController@find');
Route::get('/class/{name}', 'ClassController@detail')->name('class.detail');

//Campus form
Route::resource('/campus', 'CampusController', ['only' => ['index', 'store', 'destroy']]);
Route::get('/campus/find', 'CampusController@find');
Route::get('/campus/{name}', 'CampusController@detail')->name('campus.detail');
Route::get('/campus/class-list/{code}', 'CampusController@classList')->name('campus.class-list');

//Check unique
Route::get('/unique-std', 'UniqueController@uniqueStd');
Route::get('/unique-camp', 'UniqueController@uniqueCamp');
Route::get('/unique-period', 'UniqueController@uniquePeriod');
Route::get('/unique-course', 'UniqueController@uniqueCourse');
Route::get('/unique-staff', 'UniqueController@uniqueStaff');
Route::get('/unique-book', 'UniqueController@uniqueBook');
Route::get('/unique-position', 'UniqueController@uniquePosition');
Route::get('/unique-register', 'UniqueController@uniqueRegister');

//Period form
Route::resource('/period', 'PeriodController', ['only' => ['index', 'store', 'destroy']]);
Route::get('/period/find', 'PeriodController@find');
Route::get('/period/{name}', 'PeriodController@detail')->name('period.detail');

//Schedule form
Route::resource('/schedule', 'ScheduleController', ['only' => ['index', 'store', 'destroy', 'show']]);
Route::get('/schedule/find/{value}', 'ScheduleController@find');
Route::get('/schedule/detail/{id}', 'ScheduleController@detail')->name('schedule.detail');
Route::get('/schedule/general/index', 'ScheduleController@general')->name('schedule.general');
Route::get('/schedule/general/class/{id}', 'ScheduleController@generalClass')->name('schedule.class');
Route::get('/schedule/general/teacher/{id}', 'ScheduleController@generalTeacher')->name('schedule.teacher');

Auth::routes();

//Role
Route::resource('/role', 'RoleController', ['only' => ['index', 'store', 'destroy']]);

//User
Route::resource('/user', 'UserController', ['only' => ['index', 'store', 'destroy']]);

app/User.php
<?php

namespace App;

use App\Models\Permission;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\DB;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function hasPermission(Permission $permission) {
        $role_id = $this->role_id;
        $role_permission = DB::table('role_permission')
            ->where('role_id', '=', $role_id)
            ->get();
        foreach ($role_permission as $item) {
            if ($item->permission_id == $permission->id) {
                return true;
            }
        }
        return false;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $data = DB::table('users')
            ->join('roles', 'roles.id', '=', 'users.role_id')
            ->select('users.*', 'roles.name as role_name')
            ->paginate(7);
        $roles = Role::get();
        return view('user.user', compact('data'), compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        try {
            $user = User::updateOrCreate(['id' => $request->id], $request->all());
            return redirect()->back()->with('success',  __('action.update').__('action.success'));
        }
        catch (\Exception $ex) {
            return redirect()->back()->with('fail',  __('action.update').__('action.fail'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        try {
            $user = User::findOrFail($id)->delete();
            return redirect()->back()->with('success', __('action.delete').__('action.success'));
        }
        catch (\Exception $exception) {
            return redirect()->back()->with('fail', __('action.delete').__('action.fail'));
        }
    }
}

resources/views/user/user.blade.php
@extends('layout.master')
@section('css')
    <link rel="stylesheet" href="{{ asset('css/course.css') }}">
@endsection
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">{{ __('user.list') }}</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('home') }}">{{ __('action.home') }}</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="clearfix header-course">
                @if(session('success'))
                    <div class="alert alert-success abc" role="alert">
                        {{ session('success') }}
                    </div>
                @endif
                @if(session('fail'))
                    <div class="alert alert-danger abc" role="alert">
                        {{ session('fail') }}
                    </div>
                @endif
            </div>
            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body table-responsive">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th style="text-align: center"><input type="checkbox" id="check-all"></th>
                                <th scope="col" style="text-align: center">{{__('action.id')}}</th>
                                <th scope="col">{{__('user.name')}}</th>
                                <th scope="col">{{__('user.email')}}</th>
                                <th scope="col">{{__('user.role')}}</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $item => $user)
                                <tr>
                                    <td class="align-middle" style="text-align: center"><input type="checkbox" class="btn-check"></td>
                                    <th class="align-middle" style="text-align: center" scope="row">{{ $data->firstItem() + $item }}</th>
                                    <td class="align-middle">{{ $user->name }}</td>
                                    <td class="align-middle">{{ $user->email }}</td>
                                    <td class="align-middle">{{ $user->role_name }}</td>
                                    <td class="align-middle">
                                        <button type="button" class="btn btn-xs btn-success" data-toggle="modal" data-target="#exampleModalUpdate{{ $user->id }}">
                                            {{__('action.update')}}
                                        </button>
                                        <button type="button" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#exampleModalDelete{{ $user->id }}">
                                            {{__('action.delete')}}
                                        </button>

                                        <form class="form-container" action="{{ route('user.destroy', $user->id) }}" method="POST">
                                            <input name="_method" type="hidden" value="DELETE">
                                            <div class="modal fade" id="exampleModalDelete{{ $user->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="exampleModalLabel">{{__('user.account')}}</h5>
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            @csrf
                                                            <p>{{__('action.confirm_delete')}}</p>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">{{__('action.close')}}</button>
                                                            <button type="submit" class="btn btn-primary">{{__('action.delete')}}</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>

                                        <form class="form-container form-add" action="{{ route('user.store') }}" method="POST">
                                            <div class="modal fade" id="exampleModalUpdate{{ $user->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="exampleModalLabel">{{__('user.account')}}</h5>
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            @csrf
                                                            <div class="form-group">
                                                                <input style="display: none" type="text" name="id" class="id-std form-control" id="exampleInputStt" value="{{ $user->id }}" readonly>
                                                            </div>
                                                            <div class="form-group">
                                                                <label for="exampleInput0">{{__('user.name')}} <label class="required-p">*</label></label>
                                                                <input type="text" name="name" class="form-control" id="exampleInput0" value="{{ $user->name }}" >
                                                            </div>
                                                            <div class="form-group">
                                                                <label for="exampleInput">{{__('user.email')}} <label class="required-p">*</label></label>
                                                                <input type="email" name="email" class="form-control" id="exampleInput" value="{{ $user->email }}" >
                                                            </div>
                                                            <div class="form-group">
                                                                <label for="exampleInput1">{{__('user.role')}} <label class="required-p">*</label></label>
                                                                <select class="form-control" name="role_id" id="exampleInput1">
                                                                    @foreach($roles as $role)
                                                                        <option {{ $role->id === $user->role_id ? 'selected' : '' }} value="{{ $role->id }}">{{ $role->name }}</option>
                                                                    @endforeach
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">{{__('action.close')}}</button>
                                                            <button type="submit" class="btn btn-primary">{{__('action.update')}}</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="clearfix">
                        <div style="float: right">
                            {!! $data->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <script type="text/javascript">
        $(document).ready(function() {

            $("#check-all").click(function () {
                $('input:checkbox').not(this).prop('checked', this.checked);
            });

            $("form.form-add").each(function() {
                $(this).validate({
                    ignore: [],
                    rules: {
                        name: {
                            required: true,
                        },
                        email: {
                            required: true,
                        },
                    },
                    messages: {
                        name: {
                            required: "<?php echo __("user.name").__("action.required") ?>",
                        },
                        email: {
                            required: "<?php echo __("user.email").__("action.required") ?>",
                        },
                    },
                });
            });

        });
    </script>
@stop